### ISSUE TITLE
Upload screenshot of portal template

### ISSUE THREAD

**Issue by ofirattia** [geoserviceportal/Installations#2]
Andrey,

You can upload screenshot of the template? @AndreyAf

**Comment by AndreyAf** [comment]
YES - it will be ready soon. I updated all the libs and started working on auth system and control panel. there was bug in their repo and I fixed it. I will upload an update soon and add screenshots

**Comment by AndreyAf** [comment]
![image](https://cloud.githubusercontent.com/assets/8948383/13667743/a7dd5168-e6c0-11e5-82aa-6ae14778274b.png)

**Comment by AndreyAf** [comment]
1. I think all the subjects need to be in the left sidebar and not in the top navbar. 
2. In the top mavbar we put links to about page. blog and etc.
3. Add option to hide sidebar.

**Comment by AndreyAf** [comment]
![capture2](https://cloud.githubusercontent.com/assets/8948383/13668989/14cb6118-e6c9-11e5-8c13-fc71487bb586.PNG)

**Comment by ofirattia** [comment]
Amazing. thanks!

**Comment by AndreyAf** [comment]
![new-login-page](https://cloud.githubusercontent.com/assets/8948383/13722252/b5548662-e847-11e5-8305-92840192fb45.PNG)
