### ISSUE TITLE
please provide write access

### ISSUE THREAD

**Issue by haim100** [geoserviceportal/Installations#8]
please provide write access in order to add files to the repository.
![image](https://cloud.githubusercontent.com/assets/17828522/14189296/2e299b16-f795-11e5-9f73-31982799d9d4.png)

thanks
Haim

**Comment by AndreyAf** [comment]
You can add only to your branch - adding to master branch only with pull request. I saw your pull request in the system and there nothing wrong in current instructions because we don't need it right now - the real instructions are in the client folder.

**Comment by haim100** [comment]
Hello,
I can't add files to my branch.
Please advice.
Thanks
